=== aymen2255/tp-fichier/catalogue.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">






	<xs:element name="catalogueXML">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="raisonSociale" type="xs:string" maxOccurs="1" minOccurs="1"/>
	       		<xs:element name="dateDepot" type="xs:date" maxOccurs="1" minOccurs="1"/>
				<xs:element ref="voitureXML" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="voitureXML">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="marque" type="xs:string"/>
	      <xs:element name="modele" type="xs:string"/>
	      <xs:element name="couleur" type="xs:string"/>
	      <xs:element name="nbPortes" type="xs:int"/>
	      <xs:element name="nbPlaces" type="xs:int"/>
	      <xs:element name="equipements" type="xs:string"/>
	      <xs:element name="motorisation" type="xs:string"/>
	      <xs:element name="emissionCO2" type="xs:float"/>
	      <xs:element name="imageURL" type="xs:string"/>
	      <xs:element name="prix" type="xs:double"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>

</xs:schema>

=== aymen2255/tp-fichier/catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogueXML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="catalogue.xsd">
	<raisonSociale>raisonSociale</raisonSociale>
	<dateDepot>2001-01-01</dateDepot>
	<voitureXML>
		<marque>marque</marque>
		<modele>modele</modele>
		<couleur>couleur</couleur>
		<nbPortes>0</nbPortes>
		<nbPlaces>0</nbPlaces>
		<equipements>equipements</equipements>
		<motorisation>motorisation</motorisation>
		<emissionCO2>0.0</emissionCO2>
		<imageURL>imageURL</imageURL>
		<prix>0.0</prix>
	</voitureXML>
	<voitureXML>
		<marque>marque</marque>
		<modele>modele</modele>
		<couleur>couleur</couleur>
		<nbPortes>0</nbPortes>
		<nbPlaces>0</nbPlaces>
		<equipements>equipements</equipements>
		<motorisation>motorisation</motorisation>
		<emissionCO2>0.0</emissionCO2>
		<imageURL>imageURL</imageURL>
		<prix>0.0</prix>
	</voitureXML>
	<voitureXML>
		<marque>marque</marque>
		<modele>modele</modele>
		<couleur>couleur</couleur>
		<nbPortes>0</nbPortes>
		<nbPlaces>0</nbPlaces>
		<equipements>equipements</equipements>
		<motorisation>motorisation</motorisation>
		<emissionCO2>0.0</emissionCO2>
		<imageURL>imageURL</imageURL>
		<prix>0.0</prix>
	</voitureXML>
	<voitureXML>
		<marque>marque</marque>
		<modele>modele</modele>
		<couleur>couleur</couleur>
		<nbPortes>0</nbPortes>
		<nbPlaces>0</nbPlaces>
		<equipements>equipements</equipements>
		<motorisation>motorisation</motorisation>
		<emissionCO2>0.0</emissionCO2>
		<imageURL>imageURL</imageURL>
		<prix>0.0</prix>
	</voitureXML>
</catalogueXML>
